### ISSUE TITLE
Implement message queue for utt-bridge

### ISSUE THREAD

**Issue by fk1blow** [tradingticket/utt.js#17]
Whenever the "sendMessage" mechanism will trigger, the `@_communicationBridge` might
still be load(actually, their iframe) and thus all the send message attempts, will go to nowhere.

If the bridge isn't ready, provide a queue that will contain all the messages; when the `@_communicationBridge`(iframe)  becomes ready, drain the queue and send all the messages from it.

**Comment by teosz** [comment]
need we
